# A small bashrc file for personal/server use

# Set prompt
export PS1="\[\033[34m\]\]\W -> \[\033[37m\]\]"

# Set vim bindings
set -o vi

# Aliases

alias h="history"
alias hg="history | grep"

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias g='git'
alias ga='git add'
alias gcmsg='git commit -m'
alias gp='git push'

# Yay, look stuff up
function cheat {
    curl cheat.sh/$1
}
