export EDITOR="nvim"
export VISUAL="nvim"
export COMP_TYPE="HOME"                 # HOME, WORK, SERVER, WORK_SERVER

export DOTFILES=${HOME}/.dotfiles
export WORK_DOTFILES=${HOME}/.work-dotfiles


export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file
