export EDITOR="nvim"
export VISUAL="nvim"
export COMP_TYPE="HOME"                 # HOME, WORK, SERVER, WORK_SERVER

export DOTFILES=${HOME}/.dotfiles
export WORK_DOTFILES=${HOME}/.work-dotfiles


export HISTFILE="${HOME}/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file


# COLOR
# less
export LESSOPEN="| /usr/bin/source-highlight-esc.sh %s"
export LESS='-R --use-color -Dd+r$Du+b'
# export LESS='-R '
# man
export MANPAGER="less -R --use-color -Dd+r -Du+b"


# Path updates
. "$HOME/.cargo/env"
export PATH=${PATH}:${DOTFILES}/bin
export PATH=${PATH}:${HOME}/.bin

export PYENV_ROOT="$HOME/.pyenv"
