# theme

# Enable substitution in the prompt.
setopt prompt_subst

# Config for prompt. PS1 synonym.
autoload -U colors && colors

# prompt='$(git_branch_name) | %1/ %{$fg[cyan]%}⇒ '

source ${HOME}/.git.zsh
ZSH_THEME_GIT_PROMPT_PREFIX="%{$reset_color%}%{$fg[green]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[yellow]%}⚡%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_CLEAN=""
PROMPT='%{$fg[cyan]%}%1~%{$reset_color%}%{$fg[red]%}|%{$reset_color%}$(git_prompt_info)%{$fg[cyan]%}⇒%{$reset_color%} '

# aliases

alias ls="ls --color"

alias g="git"

alias gs="git status"

alias ga="git add"

alias gcm="git checkout main"
alias gcd="git checkout develop"
alias gcs="git checkout stage"
alias gc="git checkout"

alias gcmsg="git commit -m"

alias gp="git push"

# GO
export GOPATH="${HOME}/.go"

source /Users/pmessina/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Java
export JAVA_HOME="/Library/Java/JavaVirtualMachines/openjdk.jdk/Contents/Home"

export PATH=${PATH}:${HOME}/.bin
